[ADD] slack webhook

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,10 +10,10 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: 🔄 Checkout
+      - name: 🔄 Checkout Code
         uses: actions/checkout@v4
 
-      - name: 🛠️ Set up Java
+      - name: 🛠️ Set up Java 17
         uses: actions/setup-java@v4
         with:
           java-version: '17'
@@ -21,6 +21,13 @@ jobs:
 
       - name: 📦 Build app
         run: ./gradlew clean build -x test
+
+      - name: ✅ Check if JAR exists
+        run: |
+          if [ ! -f build/libs/*.jar ]; then
+            echo "JAR file not found!"
+            exit 1
+          fi
 
       - name: 🏷️ Rename JAR (optional)
         run: mv build/libs/*.jar build/libs/syncora.jar
@@ -34,21 +41,15 @@ jobs:
           source: "build/libs/syncora.jar"
           target: "~/syncora-prod"
 
-      - name: ✅ Check if JAR exists
-        run: |
-          if [ ! -f build/libs/syncora.jar ]; then
-            echo "JAR file not found!"
-            exit 1
-          fi
-
-      - name: 🔍 Verify JAR on server
-        uses: appleboy/ssh-action@v1.0.3
+      - name : Notify Slack About deployment
+        if: always()
+        uses: rtCamp/action-slack-notify@v2
         with:
-          host: ${{ secrets.EC2_HOST }}
-          username: ${{ secrets.EC2_USER }}
-          key: ${{ secrets.EC2_SSH_KEY }}
-          script: |
-            ls -lh /home/ubuntu/syncora-prod/syncora.jar
+          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
+          messages: |
+            🚀 Deployment to *production* branch ${{ github.ref }} by ${{ github.actor }}
+            Status: ${{ job.status }}
+          color: ${{ job.status == 'success' && 'good' || 'danger' }}
 
       - name: 🔁 Restart Spring Boot (systemd)
         uses: appleboy/ssh-action@v1.0.3
@@ -57,8 +58,11 @@ jobs:
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
+            set -e
             echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" | sudo tee /etc/syncora.env > /dev/null
             echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" | sudo tee -a /etc/syncora.env > /dev/null
+            sudo chown ubuntu:ubuntu /home/ubuntu/syncora-prod/syncora.jar
+            sudo chmod 755 /home/ubuntu/syncora-prod/syncora.jar
             sudo systemctl daemon-reload
             sudo systemctl restart syncora.service
             sudo systemctl status syncora.service --no-pager
